<div class="brands-container">
	<ul>
		<li><a href="<?php echo $this->getUrl('produse/trx.html') ?>"><img src="<?php echo $this->getSkinUrl('images/media/trx.png') ?>" alt=""></a></li>
		<li><a href="<?php echo $this->getUrl('produse/trigger-point.html') ?>"><img src="<?php echo $this->getSkinUrl('images/media/triggerpoint.png') ?>" alt=""></a></li>
		<li><a href="<?php echo $this->getUrl('produse/rejuvenation.html') ?>"><img src="<?php echo $this->getSkinUrl('images/media/rejuvenation.png') ?>" alt=""></a></li>
		<li><a href="<?php echo $this->getUrl('produse/per4m.html') ?>"><img src="<?php echo $this->getSkinUrl('images/media/per4m.png') ?>" alt=""></a></li>
		<li><a href="<?php echo $this->getUrl('produse/lifeline-usa.html') ?>"><img src="<?php echo $this->getSkinUrl('images/media/lofeline.png') ?>" alt=""></a></li>
		<li><a href="<?php echo $this->getUrl('produse/lebert-fitness.html') ?>"><img src="<?php echo $this->getSkinUrl('images/media/lebert.png') ?>" alt=""></a></li>
		<li><a href="<?php echo $this->getUrl('produse/flowin.html') ?>"><img src="<?php echo $this->getSkinUrl('images/media/flowin.png') ?>" alt=""></a></li>
	</ul>
</div>