<?php
/**
 * Mason Web Development
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2009 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
//get all Profiles 
$testimonials = $this->getTestimonials();
?>
<div class="clearer"></div>
<div id="slides" class="videos">
	<div class="section-title">
		<span>Video</span>
	</div>
	<div class="slides_container">
		<div class="slide">
			<div class="box">
				<iframe width="460" height="300" src="http://www.youtube.com/embed/rJ5O5UjAQGc" frameborder="0" allowfullscreen></iframe>
				TRX Bootcamp in Romania.<br/>
				Locatie : Pensiunea Unio, Sacele, Brasov.<br/>
				Material difuzat de DigiTv in cadrul emisiunii " Tinerete fara batranete ".
			</div>
			<div class="box right">
				<iframe width="460" height="300" src="http://www.youtube.com/embed/jKPe7oKIhBE" frameborder="0" allowfullscreen></iframe>
				Dimi cu Pete Holman. <br/> Demonstratie TRX Rip " Samurai Strike ".
			</div>
		</div>
		<div class="slide">
			<div class="box">
				<iframe width="460" height="300" src="http://www.youtube.com/embed/6ltojYUUa68" frameborder="0" allowfullscreen></iframe>
				<p style="">Acest curs de opt ore va invata bazele si nu numai a antrenamentelor cu Rip Trainer. De asemenea, veți invata și variații pentru a adapta exercițiile la fiecare nivel de fitness.<a href="<?php echo $this->getUrl('trx/trx-courses/rtc.html') ?>"> <br/>Inscrie-te aici !</a></p>
			</div>
			<div class="box right">
				<iframe width="460" height="300" src="http://www.youtube.com/embed/kfmsjI3HvHE" frameborder="0" allowfullscreen></iframe>
				<p style="">In acest curs de 8 ore veți învăța cum să efectuați corect exercițiile fundamentale de antrenament suspendat, sa corectați si îndrumați clienții in  aceste exerciții precum și beneficiile și mușchii țintă ale acestor exerciții.<a href="<?php echo $this->getUrl('trx/trx-courses/suspension-training-course.html') ?>"> <br/>Inscrie-te aici !</a></p> 
			</div>
		</div>
	</div>
</div>
<div class="clearer"></div>
<div class="page-title testimonial-title">
        <h2><?php echo $this->__('Testimoniale') ?></h2>
</div>
<div class="testimonials">
<?php foreach($testimonials as $n): ?>
	<?php if ($n->getData("is_active")):?>
		<div class="item">
			<h2><?php echo $this->formatDate($n->getData("creation_time")); ?> - <?php echo $n->getData("content_heading"); ?></h2>
			<p><?php echo $n->getContent(); ?></p>
		</div>
	<?php endif; ?>
<?php endforeach; ?>
</div>
<div class="clearer"></div>
<div class="partners">
	<div class="section-title">
		<span><?php echo $this->__('Parteneri') ?></span>
	</div>
	<div class="clearer"></div>
	<a class="left" target='_blank' href="http://www.worldclass.ro/"><img src="<?php echo $this->getSkinUrl('images/partners_worldclass.png')?>"/></a>
	<a class="right" target='_blank' href="http://www.move-on.ro/"><img src="<?php echo $this->getSkinUrl('images/partners_moveon.png')?>"/></a>
</div>