<div class="landing-page">
	<div class="left">
		<h1 class="logo"><img src="<?php echo $this->getSkinUrl('images/landing/logo-beta.png') ?>" alt="Ymall Shopping S.R.L."/></h1>
		<div class="text">
			<h2><span>Lansare BETA - </span><strong>29 noiembrie</strong></h2>
			<p>
				<strong class="subtitle">De ce am realizat Ymall?</strong>
				  
				Ne-am săturat de site-urile gen <strong>depozit</strong>, unde totul arată la fel şi experienţa de a cumpăra o carte e la fel cu cea de a cumpăra o maşină de spălat. Credem că merităm mai mult de atât şi credem că am reuşit să aducem la un alt nivel diversitatea şi libertatea de exprimare în comerţul online .
			</p>
		</div>
		<div class="text">
			<h2><span>Fă parte </span><strong>din revoluţie</strong></h2>
			<p>
				Dacă simti şi tu nevoia unei schimbări de la rutina experienţei cumpărăturilor în mediul virtual.
			</p>
		</div>
	    <form action="<?php echo $this->getUrl('newsletter/subscriber/newRevolution') ?>" method="post" id="newsletter-validate-detail">
	        <div class="block-content">
	            <div class="input-box">
	               <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Fă parte din revoluţie') ?>" class="input-text required-entry validate-email" />
	            </div>
	            <div class="actions">
	                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
	            </div>
	        </div>
	    </form>
	    <script type="text/javascript">
	    //<![CDATA[
	        var searchForm = new Varien.searchForm('newsletter-validate-detail', 'newsletter', '<?php echo $this->__('Fă parte din revoluţie') ?>');
	        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
	    //]]>
	    </script>
	</div>
	<div class="right">
		<div class="map"><a href="<?php echo str_replace('mall/', '', $this->getUrl('essenza')) ?>" title="Essenza Shopping YMall"><img src="<?php echo $this->getSkinUrl('images/landing/map.png') ?>" alt="Ymall Shopping Map" title="Ymall Shopping Map"/></a></div>
		<div class="progress no-display"><img src="<?php echo $this->getSkinUrl('images/landing/spatii-ocupate.png') ?>" alt="Ymall Shopping Map" title=""/></div>
	</div>
	<div class="footer-landing">
		<p>copyright © 2014-2015 S.C Ymall Shopping S.R.L. Toate drepturile rezervate.</p>
	</div>
</div>

<style>
	.page-empty { background: #ededed; padding: 0; }
</style>