<div class="bottom-map">
	<ul class="bxslider">
	  <li>
			<div class="image">
				<a href="<?php echo $this->getUrl('',array('_store'=>'essenza')) ?>"><img src="<?php echo $this->getSkinUrl('images/mapslider/s_map_essenza.png') ?>" alt=""></a>
			</div>
			<div class="text">
				<h3>Essenza Shoes</h3><br>
				<p>
					Etaj: <strong>Demisol</strong><br>
					Loc pe hartă: <span class="highlight">D10</span><br>
					Status: <span class="highlight">Activ</span>
				</p><br>
				<button onclick="setLocation('<?php echo $this->getUrl('',array('_store'=>'essenza')) ?>')" class="button"><span><i class="fa fa-arrow-circle-right"></i><span>vizitează</span></span></button>
			</div>
	  </li>
	  <li>
			<div class="image">
				<img src="<?php echo $this->getSkinUrl('images/mapslider/s_map_spyshop.png') ?>" alt="">
			</div>
			<div class="text">
				<h3>Spy Shop - Echipamente de securitate</h3><br>
				<p>
					Etaj: <strong>Demisol</strong><br>
					Loc pe hartă: <span class="highlight">D4</span><br>
					Status: <span class="highlight">Inactiv</span><br>
					Lansare: <span class="highlight">22.02.2015</span>
				</p>
			</div>
	  </li>
	  <li>
			<div class="image">
				<img src="<?php echo $this->getSkinUrl('images/mapslider/s_map_spyshop.png') ?>" alt="">
			</div>
			<div class="text">
				<h3>Spy Shop - Echipamente de securitate</h3><br>
				<p>
					Etaj: <strong>Demisol</strong><br>
					Loc pe hartă: <span class="highlight">D3</span><br>
					Status: <span class="highlight">Inactiv</span><br>
					Lansare: <span class="highlight">22.02.2015</span>
				</p>
			</div>
	  </li>
	</ul>
</div>

<script>
	jQuery(document).ready(function(){
		jQuery('.bxslider').bxSlider({
			// GENERAL
			mode: 'horizontal',
			useCSS: false,
			tickerHover: true,
			infiniteLoop: false,

			// PAGER
			pager: false,

			// CONTROLS
			controls: true,
			nextText: 'Next',
			prevText: 'Prev',
			nextSelector: null,
			prevSelector: null,
			autoControls: false,
			startText: 'Start',
			stopText: 'Stop',
			autoControlsCombine: false,
			autoControlsSelector: null,

			// AUTO
			auto: true,
			pause: 7000,

			// CAROUSEL
			minSlides: 1,
			maxSlides: 2,
			moveSlides: 1,
			slideWidth: 542,
  			slideMargin: 20,
		});
	});
</script>