<div class="right-map">
	<div class="map">
		<a href="<?php echo $this->getUrl('',array('_store'=>'essenza')); ?>"><img class="main-img" src="<?php echo $this->getSkinUrl('images/mapslider/essenza_map.png') ?>" alt="" /></a>
		<img class="preload no-display" src="<?php echo $this->getSkinUrl('images/mapslider/essenza_map_hover.png') ?>" alt="" />
	</div>
	<div class="map-disabled">
		<img class="main-img" src="<?php echo $this->getSkinUrl('images/mapslider/map_spyshop.png') ?>" alt="" />
	</div>
	<div class="map-disabled">
		<img class="main-img" src="<?php echo $this->getSkinUrl('images/mapslider/map_greenfuture.png') ?>" alt="" />
	</div>
</div>

<script>
	jQuery('.map').each(function(){
		jQuery(this).hover(function() {
			jQuery(this).find('.main-img').attr({"src":"<?php echo $this->getSkinUrl('images/mapslider/essenza_map_hover.png') ?>","style":"margin:-24px 0 -25px;"});
		}, function() {
			jQuery(this).find('.main-img').attr({"src":"<?php echo $this->getSkinUrl('images/mapslider/essenza_map.png') ?>","style":"margin:0;"});
		});
	});
</script>