<?php
	$bannerCollection = $this->getBannerCollection();
	$i = 0;
?>
<?php $timeDelay = $this->getDelayTime() ?>
<?php $showdesc = $this->isShowDescription() ?>
<?php $listStyle = $this->getListStyle() ?>
<?php $imagewidth = $this->getImageWidth() ?>
<?php $imageheight = $this->getImageHeight() ?>
<?php if(count($bannerCollection) > 0) : ?>
        <div class="slider-wrapper theme-default">
            <div id="slider2" class="nivoSlider">
				<?php $i = 0; foreach ($bannerCollection as $banner): $i++; ?>
					<a href="<?php echo $banner['weblink'];?>">
						<img data-thumb="<?php echo $banner['content']?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" alt="<?php echo $banner['title']?>" style="width:<?php echo $imagewidth;?>px; height:<?php echo $imageheight;?>px;" />
					</a>
				<?php endforeach; ?>				
            </div>

        </div>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.nivo.slider.js') ?>"></script>
		
		<script type="text/javascript">
			jQuery(window).load(function() {
				jQuery('#slider2').nivoSlider({
				effect: 'fold', // Specify sets like: 'fold,fade,sliceDown'
				slices: 15, // For slice animations
				boxCols: 8, // For box animations
				boxRows: 4, // For box animations
				animSpeed: 600, // Slide transition speed
				pauseTime: 5000, // How long each slide will show
				startSlide: 0, // Set starting Slide (0 index)
				directionNav: true, // Next & Prev navigation
				controlNav: true, // 1,2,3... navigation
				controlNavThumbs: true, // Use thumbnails for Control Nav
				pauseOnHover: true, // Stop animation while hovering
				manualAdvance: false, // Force manual transitions
				prevText: 'Prev', // Prev directionNav text
				nextText: 'Next', // Next directionNav text
				randomStart: false, // Start on a random slide
				beforeChange: function(){}, // Triggers before a slide transition
				afterChange: function(){}, // Triggers after a slide transition
				slideshowEnd: function(){}, // Triggers after all slides have been shown
				lastSlide: function(){}, // Triggers when last slide is shown
				afterLoad: function(){} // Triggers when slider has loaded
			});
			});
		</script>		
<?php endif; ?>
<div class="clear"></div>