<?php
/**
 * Mason Web Development
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2009 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php 
// get all News 
$news = $this->getNews();
?>
<?php if ($news->count() > 0) : ?>
<div class="news">
	<div class="section-title">
		<span><?php echo $this->__('Stiri')?></span>
	</div>
	<ul class="news-content">
	<?php $i=0; foreach($news as $n): $i++; ?>
		<?php if ($n->getData("is_active")):?>
			<li <?php if ($i%2==0) : ?>class="even"<?php else: ?>class="odd"<?php endif; ?> >
				<?php $newsUrl = $this->getUrl('profile/news/read', array("id" => $n->getData("profile_id")));?>
				<h2><?php echo $n->getData("content_heading"); ?></h2>
				<span class="date"><?php echo $this->formatDate($n->getData("creation_time")); ?></span>
				<span class="content"><?php echo $n->getContent(100); ?></span>
				<a class="read-more" href="<?php echo $newsUrl ?>">
					<?php if ($i%2==0) : ?>
						<img src="<?php echo $this->getSkinUrl('images/news-array-grey.jpg')?>"/>
					<?php else: ?>
						<img src="<?php echo $this->getSkinUrl('images/news-read.png')?>"/>
					<?php endif; ?>
				</a>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
	</ul>
	<a href="<?php echo $this->getUrl('profile/news') ?>" class="see-all"><?php echo $this->__('Citeste toate stirile')?><span>></span></a>
</div>
<?php endif; ?> 


	

