<?php 
    $_storeCode = Mage::app()->getStore()->getCode();
    if($_storeCode!='mall'):
?>
<div class="store-menu-container">
	<div class="store-menu">
		<div class="store-logo">
			<h3><a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getSkinUrl('images/logos/spyshop.png') ?>" alt=""></a></h3>
		</div>
		<span>Adevărul prin tehnologie!</span>
		<div class="mobile-menu"><?php echo $this->__('Meniu') ?></div>
		<div class="menu">
			<ul class="menu-links">
				<li><a href="<?php echo $this->getUrl('') ?>"><?php echo $this->__('Home') ?></a></li>
				<li><a href="<?php echo $this->getUrl('toate-produsele.html') ?>"><?php echo $this->__('Produse') ?></a></li>
				<li><a href="<?php echo $this->getUrl('despre-noi') ?>"><?php echo $this->__('Despre noi') ?></a></li>
				<li><a href="<?php echo $this->getUrl('contacts') ?>"><?php echo $this->__('Contact') ?></a></li>
			</ul>
			<?php echo $this->getChildHtml('topMenu') ?>
		</div>
	</div>
</div>
<script>
	jQuery('.mobile-menu').click(function(){
		jQuery('.menu').slideToggle('fast');
	})
</script>
<?php endif; ?>