<div class="home-blocks col3">
	<div class="block" onclick="setLocation('<?php echo $this->getUrl('blog/category/prevent') ?>')">
		<div class="pattern"></div>
		<a class="img" href="<?php echo $this->getUrl('blog/category/prevent') ?>"><img src="<?php echo $this->getSkinUrl('images/media/prevent.jpg') ?>" alt="" /></a>
		<div class="home-hover-data">
			<div class="table-full text-center">
				<div>
					<div>
						<a class="title" href="<?php echo $this->getUrl('blog/category/prevent') ?>"><h3>Prevent</h3></a>
					</div>
				</div>
			</div>
		</div>
		<span class="desc">Te ajutam sa previ accidentarile</span>
	</div>
	<div class="block" onclick="setLocation('<?php echo $this->getUrl('blog/category/perform') ?>')">
		<div class="pattern"></div>
		<a class="img" href="<?php echo $this->getUrl('blog/category/perform') ?>"><img src="<?php echo $this->getSkinUrl('images/media/perform.jpg') ?>" alt="" /></a>
		<div class="home-hover-data">
			<div class="table-full text-center"> 
				<div>
					<div>
						<a class="title" href="<?php echo $this->getUrl('blog/category/perform') ?>"><h3>Perform</h3></a>
					</div>
				</div>
			</div>
		</div>
		<span class="desc">Antreneaza-te cu noi, oriunde ai fi.</span>
	</div>
	<div class="block" onclick="setLocation('<?php echo $this->getUrl('blog/category/recover') ?>')">
		<div class="pattern"></div>
		<a class="img" href="<?php echo $this->getUrl('blog/category/recover') ?>"><img src="<?php echo $this->getSkinUrl('images/media/ColdRoller_lats.jpg') ?>" alt="" /></a>
		<div class="home-hover-data">
			<div class="table-full text-center">
				<div>
					<div>
						<a class="title" href="<?php echo $this->getUrl('blog/category/recover') ?>"><h3>Recover</h3></a>
					</div>
				</div>
			</div>
		</div>
		<span class="desc">Recuperarea este la fel de importanta ca antrenamentul.</span>
	</div>
</div>
<div class="noutati">
	<div class="page-title">
        <h2>Noutati</h2>
    </div>
    <div class="blocks">
    	<div class="block">
    		<div class="title">
    			<?php echo $this->__('TRX Special Force') ?>
    		</div>
    		<a href="<?php echo $this->getUrl('blog/category/solutii-pentru-profesionisti') ?>"><img src="<?php echo $this->getSkinUrl('images/media/trx_special_force.png') ?>" alt=""></a>
			<span class="desc">Cel mai ambitios proiect de pana acum in care ne implicam.</span>
    	</div>
    	<div class="block">
    		<div class="title">
    			<?php echo $this->__('D.I.M.I Partener Oficial Steaua') ?>
    		</div>
    		<a href="<?php echo $this->getUrl('blog/blog/trx-makes-champions-istoria-dovedit-o-prezentul-o-confirma') ?>"><img src="<?php echo $this->getSkinUrl('images/media/partener_steaua_oficial.png') ?>" alt=""></a>
			<span class="desc">D.I.M.I sustine fotbalul romanesc.</span>
    	</div>
    </div>
</div>
<div class="home-blocks col4">
	<div class="block" onclick="setLocation('<?php echo $this->getUrl('centre-de-fitness-si-cluburi-sportive.html') ?>')">
		<div class="pattern"></div>
		<a class="img" href="<?php echo $this->getUrl('centre-de-fitness-si-cluburi-sportive.html') ?>"><img src="<?php echo $this->getSkinUrl('images/media/solutii-pro-manchastercity.jpg') ?>" alt="" /></a>
		<div class="home-hover-data">
			<div class="table-full text-center">
				<div>
					<div>
						<a class="title" href="<?php echo $this->getUrl('centre-de-fitness-si-cluburi-sportive.html') ?>"><h3>Solutii pentru PROfesionisti</h3></a>
					</div>
				</div>
			</div>
		</div>
		<span class="desc">Indiferent de sport avem solutia pentru tine.</span>
	</div>
	<div class="block" onclick="setLocation('<?php echo $this->getUrl('blog/category/antreneaza-te-acasa') ?>')">
		<div class="pattern"></div>
		<a class="img" href="<?php echo $this->getUrl('blog/category/antreneaza-te-acasa') ?>"><img src="<?php echo $this->getSkinUrl('images/media/Shot_03_086.jpg') ?>" alt="" /></a>
		<div class="home-hover-data">
			<div class="table-full text-center">
				<div>
					<div>
						<a class="title" href="<?php echo $this->getUrl('blog/category/antreneaza-te-acasa') ?>"><h3>Antreneaza-te ACASA</h3></a>
					</div>
				</div>
			</div>
		</div>
		<span class="desc">Nu trebuie sa mergi la sala ca se te antrenezi.</span>
	</div>
	<div class="block" onclick="setLocation('<?php echo $this->getUrl('concepte.html') ?>')">
		<div class="pattern"></div>
		<a class="img" href="<?php echo $this->getUrl('concepte.html') ?>"><img src="<?php echo $this->getSkinUrl('images/media/TRX_GSTC_Other_060.jpg') ?>" alt="" /></a>
		<div class="home-hover-data">
			<div class="table-full text-center">
				<div>
					<div>
						<a class="title" href="<?php echo $this->getUrl('concepte.html') ?>"><h3>Concepte</h3></a>
					</div>
				</div>
			</div>
		</div>
		<span class="desc">Solutii complete pentru afacerea ta.</span>
	</div>
	<div class="block" onclick="setLocation('<?php echo $this->getUrl('blog/category/media') ?>')">
		<div class="pattern"></div>
		<a class="img" href="<?php echo $this->getUrl('blog/category/media') ?>"><img src="<?php echo $this->getSkinUrl('images/media/Cover-1-MH-Noiembrie-2013-CROP-354x332.jpg') ?>" alt="" /></a>
		<div class="home-hover-data">
			<div class="table-full text-center">
				<div>
					<div>
						<a class="title" href="<?php echo $this->getUrl('blog/category/media') ?>"><h3>Media</h3></a>
					</div>
				</div>
			</div>
		</div>
		<span class="desc">Vezi cine vorbeste despre noi.</span>
	</div>
</div>