<ul class="blocks">
	<li>
		<img src="<?php echo $this->getSkinUrl('images/1.png')?>"/>
		<h2>Power Bodybuilding</h2>
		<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi<a href=""><img src="<?php echo $this->getSkinUrl('images/read-array.png')?>"/></a></span>		
	</li>
	<li>
		<img src="<?php echo $this->getSkinUrl('images/3.png')?>"/>
		<h2>Power Bodybuilding</h2>
		<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi<a href=""><img src="<?php echo $this->getSkinUrl('images/read-array.png')?>"/></a></span>
	</li>
	<li class="last">
		<img src="<?php echo $this->getSkinUrl('images/5.png')?>"/>
		<h2>Power Bodybuilding</h2>
		<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi<a href=""><img src="<?php echo $this->getSkinUrl('images/read-array.png')?>"/></a></span>
	</li>
	<li>
		<img src="<?php echo $this->getSkinUrl('images/2.png')?>"/>
		<h2>Power Bodybuilding</h2>
		<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi<a href=""><img src="<?php echo $this->getSkinUrl('images/read-array.png')?>"/></a></span>
	</li>
	<li>
		<img src="<?php echo $this->getSkinUrl('images/4.png')?>"/>
		<h2>Power Bodybuilding</h2>
		<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi<a href=""><img src="<?php echo $this->getSkinUrl('images/read-array.png')?>"/></a></span>
	</li>
	<li class="last">
		<img src="<?php echo $this->getSkinUrl('images/6.png')?>"/>
		<h2>Power Bodybuilding</h2>
		<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi<a href=""><img src="<?php echo $this->getSkinUrl('images/read-array.png')?>"/></a></span>
	</li>
</ul>
<div class="latest-posts">
	<div class="section-title">
		<span>Latest Posts</span>
	</div>
	<ul class="content">
		<li>	
			<img src="<?php echo $this->getSkinUrl('images/post1.png')?>"/>
			<h2>Work harder, and give more than anyone else</h2>
			<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
			<span class="read-more">read more</span>
		</li>
		<li>	
			<img src="<?php echo $this->getSkinUrl('images/post2.png')?>"/>
			<h2>Work harder, and give more than anyone else</h2>
			<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
			<span class="read-more">read more</span>
		</li>
		<li>	
			<img src="<?php echo $this->getSkinUrl('images/post3.png')?>"/>
			<h2>Work harder, and give more than anyone else</h2>
			<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
			<span class="read-more">read more</span>
		</li>
	</ul>
	<a href="" class="see-all">See all Posts<span>></span></a>
</div>
<div class="news">
	<div class="section-title">
		<span>News</span>
	</div>
	<ul class="news-content">
		<li class="odd">	
			<h2>Fitness event 2012</h2>
			<span class="date">09.10.2012- Health Academy at the Grand</span>
			<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt .</span>
			<a href=""><img src="<?php echo $this->getSkinUrl('images/news-array-grey.jpg')?>"/></a>
		</li>
		<li class="even">	
			<h2>Fitness event 2012</h2>
			<span class="date">09.10.2012- Health Academy at the Grand</span>
			<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt .</span>
			<a href=""><img src="<?php echo $this->getSkinUrl('images/news-read.png')?>"/></a>
		</li>
		<li class="odd">	
			<h2>Fitness event 2012</h2>
			<span class="date">09.10.2012- Health Academy at the Grand</span>
			<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt .</span>
			<a href=""><img src="<?php echo $this->getSkinUrl('images/news-array-grey')?>"/></a>
		</li>
		<li class="even">	
			<h2>Fitness event 2012</h2>
			<span class="date">09.10.2012- Health Academy at the Grand</span>
			<span class="content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt .</span>
			<a href=""><img src="<?php echo $this->getSkinUrl('images/news-read.png')?>"/></a>
		</li>
	</ul>
</div>
<div class="videos">
	<div class="section-title">
		<span>Videos</span>
	</div>
</div>
<div class="partners">
	<div class="section-title">
		<span>Our Partners</span>
	</div>
	<img src="<?php echo $this->getSkinUrl('images/partners.jpg')?>"/>
</div>