<div class="stores-container">
	<div class="title">
		Magazine
	</div>
	<div class="stores-content">
		<ul class="store-list">
			<li>
				<div class="image"><a href="http://dev.dan-lucian.com/ymall2/essenza/"><img src="<?php echo $this->getSkinUrl('images/media/essenza_banner.jpg') ?>" alt="Essenza Shose Store"/></a></div>
				<div class="info">
					<div class="store-logo"><a href="http://dev.dan-lucian.com/ymall2/essenza/"><img src="<?php echo $this->getSkinUrl('images/logos/essenza_logo.png') ?>" alt="Essenza Shose Store"/></a></div>
					<a href="http://dev.dan-lucian.com/ymall2/essenza/" class="store-name"><?php echo $this->__('Essenza Store') ?></a>
					<div class="rating"></div>
				</div>
			</li>
		</ul>
	</div>
</div>